# Generated by Django 4.0 on 2024-04-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_alter_news_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_time']},
        ),
    ]
